twig:
  default_path: '%kernel.project_dir%/templates'
  globals:
    publicRootDir: '%kernel.project_dir%/public'
    frontUrl: '%env(FRONT_URL)%'
    backUrl: '%env(BACK_URL)%'
    etablissementNom: '%env(ETABLISSEMENT_NOM)%'
    serviceNom: '%env(SERVICE_NOM)%'
    etablissementVille: '%env(ETABLISSEMENT_VILLE)%'
    etablissementAdresseRue: '%env(ETABLISSEMENT_ADRESSE_RUE)%'
    etablissementAdressePostale: '%env(ETABLISSEMENT_ADRESSE_POSTALE)%'
    afficherServiceReferent: '%env(bool:AFFICHER_SERVICE_REFERENT)%'
    tribunalAdministratifVille: '%env(TRIBUNAL_ADMINISTRATIF_VILLE)%'
    tribunalAdministratifAdresse: '%env(TRIBUNAL_ADMINISTRATIF_ADRESSE)%'
  paths:
    '%kernel.project_dir%/public/css': 'styles'

when@test:
  twig:
    strict_variables: true
